[package]
name = "muy_zipido"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.1.2"
reqwest = { version = "0.12.23", features = ["blocking", "stream"] }
tokio = { version = "1.47.1", features = ["full"] }
